"""create user_token table

Revision ID: c82aa89c2812
Revises: ecde5522be46
Create Date: 2025-10-27 16:45:17.965626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82aa89c2812'
down_revision: Union[str, None] = 'ecde5522be46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_key', sa.String(length=250), nullable=True),
    sa.Column('refresh_key', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_access_key'), 'user_token', ['access_key'], unique=False)
    op.create_index(op.f('ix_user_token_refresh_key'), 'user_token', ['refresh_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token_refresh_key'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_access_key'), table_name='user_token')
    op.drop_table('user_token')
    # ### end Alembic commands ###
