"""create user table

Revision ID: ecde5522be46
Revises: 7d0e14321aa6
Create Date: 2025-10-09 20:50:03.858226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecde5522be46'
down_revision: Union[str, None] = '7d0e14321aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_mobile', table_name='users')
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('ix_users_mobile', 'users', ['mobile'], unique=False)
    # ### end Alembic commands ###
